-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 21:15:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventos` DEFAULT CHARACTER SET utf8mb4 ;
USE `eventos` ;

-- -----------------------------------------------------
-- Table `eventos`.`logistico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`logistico` (
  `IdLog` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(50) NOT NULL,
  `Cant` INT(30) NOT NULL,
  PRIMARY KEY (`IdLog`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`persona` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Edad` INT(20) NOT NULL,
  `Correo` VARCHAR(40) NOT NULL,
  `Pass` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`sitio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`sitio` (
  `IdSitio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Capacidad` INT(30) NOT NULL,
  `FechaIni` DATE NOT NULL,
  `Ubicacion` VARCHAR(50) NOT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`IdSitio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`solicitud` (
  `IdPeticion` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(25) NOT NULL,
  `Descripcion` VARCHAR(50) NOT NULL,
  `persona_Id` INT NOT NULL,
  `logistico_IdLog` INT NOT NULL,
  `sitio_IdSitio` INT NOT NULL,
  PRIMARY KEY (`IdPeticion`),
  INDEX `fk_solicitud_persona1_idx` (`persona_Id` ASC) ,
  INDEX `fk_solicitud_logistico1_idx` (`logistico_IdLog` ASC) ,
  INDEX `fk_solicitud_sitio1_idx` (`sitio_IdSitio` ASC) ,
  CONSTRAINT `fk_solicitud_persona1`
    FOREIGN KEY (`persona_Id`)
    REFERENCES `eventos`.`persona` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_logistico1`
    FOREIGN KEY (`logistico_IdLog`)
    REFERENCES `eventos`.`logistico` (`IdLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_sitio1`
    FOREIGN KEY (`sitio_IdSitio`)
    REFERENCES `eventos`.`sitio` (`IdSitio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
